//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HSceneCrowdReaction.Resources.ListResources", typeof(ListResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 AnimName,CategoryID,AnimID,Actor,MouthType,Lefthand,RightHand,LeftFoot,RightFoot,Penis
        ///キス,0,0,male1,Kiss,ShoulderR,ShoulderL,NoChange,NoChange,NoChange
        ///キス,0,0,female1,Kiss,BackR,BackL,NoChange,NoChange,NoChange
        /// 的當地語系化字串。
        /// </summary>
        internal static string HAnimation {
            get {
                return ResourceManager.GetString("HAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Personality,PositionType,VoicePaceType,asset
        ///OfficeLadyTypeA,AibuKiss,Idle,rg_hk_00_015
        ///OfficeLadyTypeA,AibuKiss,WLoop1,rg_hk_00_040
        ///OfficeLadyTypeA,AibuKiss,WLoop1,rg_hk_00_041
        ///OfficeLadyTypeA,AibuKiss,WLoop1,rg_hk_00_042
        ///OfficeLadyTypeA,AibuKiss,WLoop2,rg_hk_00_043
        ///OfficeLadyTypeA,AibuKiss,WLoop2,rg_hk_00_044
        ///OfficeLadyTypeA,AibuKiss,WLoop2,rg_hk_00_045
        ///OfficeLadyTypeA,AibuKiss,SLoop1,rg_hk_00_076
        ///OfficeLadyTypeA,AibuKiss,SLoop1,rg_hk_00_077
        ///OfficeLadyTypeA,AibuKiss,SLoop1,rg_hk_00_078
        ///OfficeLa [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string HVoice {
            get {
                return ResourceManager.GetString("HVoice", resourceCulture);
            }
        }
    }
}
